name: Publish NPM packages
run-name: Publish NPM packages
on:
  push:
    branches:
      - main
    # types: [closed]
#############################################################################################
jobs:
#############################################################################################
  GET-CHANGED-FILES:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      changed_packages: ${{ steps.changed-files.outputs.all_changed_files	}}
    #
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    #
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files: |
          packages/**
############################################################################################################
  RELEASE:
    if: needs.GET-CHANGED-FILES.outputs.changed_packages != ''
    needs:
      - GET-CHANGED-FILES
    strategy:
      matrix:
        package: ${{ fromJson(needs.GET-CHANGED-FILES.outputs.changed_packages) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print package
        run: | 
          echo "${{ needs.GET-CHANGED-FILES.outputs.changed_packages }}"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Get into package folder
        run: | 
          cd ${{ matrix.package }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}