name: Publish NPM packages
run-name: Publish NPM packages
on:
  push:
    branches:
      - main
    # types: [closed]
#############################################################################################
jobs:
#############################################################################################
  GET-VERSION:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.bump_version.outputs.version_tag }}
      changed_packages: ${{ steps.filter.outputs.packages_files }}
    #
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    #
    - name: Bump version
      id: bump_version
      uses: paulhatch/semantic-version@v5.0.2
    #
    - name: Get changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          packages:
            - 'packages/**/**'
    - name: print outputs
      run: |
        echo "version: ${{ needs.GET-VERSION.outputs.tag_version }}"
        echo "packages: ${{ needs.GET-VERSION.outputs.changed_packages }}"
#   PUBLISH:
#     runs-on: ubuntu-latest
#     name: Update resources by VPA
#     steps:
# #############################################################################################
#       - name: Checkout repository
#         uses: actions/checkout@v3